export const base = {
  plugins: ["typescript", "unicorn", "oxc"],
  categories: {
    correctness: "warn",
  },
  rules: {
    eqeqeq: "error",
    "no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      },
    ],
    "typescript/no-explicit-any": "error",
    "typescript/no-empty-object-type": [
      "error",
      {
        allowInterfaces: "with-single-extends",
      },
    ],
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-wrapper-object-types": "error",
    "oxc/bad-array-method-on-arguments": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-match-all-arg": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/missing-throw": "error",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-const-enum": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/uninvoked-array-callback": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-new-array": "error",
    "unicorn/no-single-promise-in-promise-methods": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-useless-fallback-in-spread": "warn",
    "unicorn/prefer-set-size": "error",
  },
}

export default base
